# Generated by Django 3.0.3 on 2020-03-06 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.IntegerField(null=True),
        ),
    ]
