# Generated by Django 3.0.3 on 2020-03-06 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
