# Generated by Django 3.0.3 on 2020-03-06 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200306_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='join',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='planning_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='thanks',
            field=models.CharField(default='お礼', max_length=200),
        ),
    ]
