# Generated by Django 3.0.3 on 2020-03-06 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200306_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(default='タイトル', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='help',
            field=models.CharField(default='手伝いを書こう', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.CharField(default='地域を選ぼう', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='thanks',
            field=models.CharField(default='地域体験を書こう', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(default='性別', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_name',
            field=models.CharField(default='名前', max_length=100),
        ),
    ]
