# Generated by Django 3.0.3 on 2020-03-06 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20200306_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
    ]
