# Generated by Django 3.0.3 on 2020-03-06 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20200306_1037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='time',
            new_name='parttime',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='u_name',
            new_name='username',
        ),
    ]
